name: Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ["ubuntu-latest"]
    steps:

    - uses: actions/checkout@v4

    - uses: 'actions-go/build@main'
      id: build-action
      with:
        action_path: ./cmd/action
        action: ${{ github.action }}

    - name: Run CI script
      run: '${{ steps.build-action.outputs.install-path }}'
